spring.application.name=party-service

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db

# Database username
spring.datasource.username=admin

# Database password
spring.datasource.password=admin

# Postgres Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto table creation (use carefully)
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true
